company = \
    {
        "Arotech Corporation" : "ARTX",
        #"Amazon.com, Inc." : "AMZN",
        "Microsoft Corporation" : "MSFT",
        "The Boeing Company" : "BA",
        "Netflix, Inc." : "NFLX",
        "BP p.l.c." : "BP",
        "Exxon Mobil Corporation" : "XOM",
        "The Goldman Sachs Group, Inc." : "GS",
        #"Internation Business Machines Corporation" : "IBM",
        "McDonald's Corporation" : "MCD",
        "Walmart Inc." : "WMT",
        "Pfizer Inc." : "PFE",
        "La-Z-boy Incorporated" : "LZB",
        "MBT Financial Corp." : "MBTF",
        "Northwest Pipe Company" : "NWPX",
        #"The Hackett Group, Inc." : "HCKT",
        "Kite Realty Group Trust" : "KRG",
        "Matthews International Corporation" : "MATW",
        "South Jersey Industries, Inc." : "SJI",
        "Crocs, Inc." : "CROX",
        "Alphabet Inc." : "GOOG",
        "El Paso Electric Company" : "EE",
        "1-800-FLOWERS.COM, Inc." : "FLWS",
        "Aerojet Rocketdyne Holdings, Inc." : "AJRD",
        "Alamo Group Inc." : "ALG",
        "Ferro Corporation" : "FOE",
        "Federal Signal Corporation" : "FSS",
        "GATX Corporation" : "GATX",
        "The Home Depot, Inc." : "HD",
        "The Coca-Cola Company" : "KO",
        "Columbia Sportswear Company" : "COLM",
        "Raytheon Company" : "RTN",
        "Caterpillar Inc." : "CAT",
        "Deere & Company" : "DE",
        "3M Company" : "MMM",
        "HMS Holdings Corp." : "HMSY",
        "Ford Motor Company" : "F",
        "JPMorgan Chase & Co." : "JPM",
        "Maxwell Technologies, Inc." : "MXWL",
        "MINDBODY, Inc." : "MB",
        #"National Beverage Corp." : "FIZZ",
        "Penn National Gaming, Inc." : "PENN",
        "Pier 1 Imports, Inc." : "PIR",
        "PulteGroup, Inc." : "PHM",
        #"ManTech International Corporation" : "MANT",
        "Sabra Health Care REIT, Inc." : "SBRA",
        "Steelcase Inc." : "SCS",
        "Shutterfly, Inc." : "SFLY",
        "Johnson & Johnson" : "JNJ",
        "General Electric Company" : "GE",
        "Intel Corporation" : "INTC",
        "Simpson Manufacturing Co., Inc." : "SSD",
        "Viad Corp" : "VVI",
        "Verizon Communications Inc." : "VZ",
        "Unit Corporation" : "UNT",
        "E*TRADE Financial Corporation" : "ETFC",
        "WD-40 Company" : "WDFC",
        "NeoGenomics, Inc." : "NEO",
        "NETGEAR, Inc." : "NTGR",
        "Century Aluminum Company" : "CENX",
        "NuVasive, Inc." : "NUVA",
        "The Gap, Inc." : "GPS",
        "Sparton Corporation" : "SPA",
        "Olympic Steel, Inc." : "ZEUS",
        "Curtiss-Wright Corporation" : "CW",
        "The Eastern Company" : "EML",
        "Dean Foods Company" : "DF",
        "Cray Inc." : "CRAY",
        "World Wrestling Entertainment, Inc." : "WWE",
        "ePlus inc." : "PLUS",
        "Exponent, Inc." : "EXPO",
        "NIKE, Inc." :  "NKE"
    }

market_index = \
    {
        "S&P 500" : "^GSPC",
        "Dow Jones Industrial Average" : "^DJI",
        "Russell 2000 Index" : "^RUT"
    }
